default:
  http_metas:
    content-type: text/html

  metas:
    title:        MooTools Forge
    description:  MooTools Plugins directory
    language:     en
    robots:       index, follow

  stylesheets:    [bootstrap.css, forge.css]

  javascripts:    [mootools-1.2.2-core+more.js, lighter.js, passshark.js, pluginskit.js, fancyzoom.js, fancyzoom.html.js]

  has_layout:     on
  layout:         layout
